//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finance_Tracking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Academic_Record
    {
        public int Student_Number { get; set; }
        public string Institution_Name { get; set; }
        public System.DateTime Academic_Year { get; set; }
        public string Qualification { get; set; }
        public Nullable<decimal> Avarage_Marks { get; set; }
        public string Upload_Transcript { get; set; }
    }
}
