//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finance_Tracking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int Application_ID { get; set; }
        public string Student_Identity_Number { get; set; }
        public string Bursary_Name { get; set; }
        public Nullable<System.DateTime> Funding_Year { get; set; }
        public string Application_Status { get; set; }
        public string Upload_Agreement { get; set; }
        public string Upload_Signed_Agreement { get; set; }
    }
}
