//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finance_Tracking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bursar_Fund
    {
        public int Application_ID { get; set; }
        public string Update_Fund_Request { get; set; }
        public string Funding_Status { get; set; }
        public string Approved_Funds { get; set; }
    }
}
