//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finance_Tracking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bursary
    {
        public string Bursary_Name { get; set; }
        public System.DateTime Start_Date { get; set; }
        public string Funder_Tax_Number { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public Nullable<decimal> Bursary_Amount { get; set; }
        public Nullable<decimal> Number_Available { get; set; }
        public string Description { get; set; }
    }
}
