//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finance_Tracking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Emp_ID { get; set; }
        public string Emp_FName { get; set; }
        public string Emp_LName { get; set; }
        public string Emp_Telephone_Number { get; set; }
        public string Emp_Email { get; set; }
        public string Emp_Office_Number { get; set; }
        public string Emp_Type { get; set; }
        public string Password { get; set; }
        public string Admin { get; set; }
        public string Admin_Conde { get; set; }
    }
}
