//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finance_Tracking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrolled_At
    {
        public string Qualification { get; set; }
        public string Student_Identity_Number { get; set; }
        public string Institution_Name { get; set; }
        public string Student_Email { get; set; }
        public string Student_Number { get; set; }
        public string Study_Residential_Address { get; set; }
    }
}
