//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finance_Tracking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Finacial_Record
    {
        public int Student_Number { get; set; }
        public string Institution_Name { get; set; }
        public Nullable<System.DateTime> Academic_Year { get; set; }
        public Nullable<decimal> Balance_Amount { get; set; }
        public string Upload_Statement { get; set; }
        public string Funding_Status { get; set; }
        public string Request_Funds { get; set; }
    }
}
