//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finance_Tracking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funder
    {
        public string Funder_Tax_Number { get; set; }
        public string Bursary_Name { get; set; }
        public string Funder_Name { get; set; }
        public string Funder_Email { get; set; }
        public string Funder_Telephone_Number { get; set; }
        public string Funder_Physical_Address { get; set; }
    }
}
