//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finance_Tracking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Institution
    {
        public int Institution_ID { get; set; }
        public string Institution_Name { get; set; }
        public string Institution_Physical_Address { get; set; }
        public string Institution_Postal_Address { get; set; }
        public string Institution_Telephone_Number { get; set; }
        public string Institution_Email_Address { get; set; }
    }
}
