//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finance_Tracking
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Finance_tracking_DatabaseEntities : DbContext
    {
        public Finance_tracking_DatabaseEntities()
            : base("name=Finance_tracking_DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Academic_Record> Academic_Records { get; set; }
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<Bursar_Fund> Bursar_Funds { get; set; }
        public virtual DbSet<Bursary> Bursaries { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Enrolled_At> Enrolled_Ats { get; set; }
        public virtual DbSet<Finacial_Record> Finacial_Records { get; set; }
        public virtual DbSet<Funder> Funders { get; set; }
        public virtual DbSet<Institution> Institutions { get; set; }
        public virtual DbSet<Student> Students { get; set; }
    }
}
