//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finance_Tracking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int UserID { get; set; }
        public string Student_FName { get; set; }
        public string Student_LName { get; set; }
        public int Student_Identity_Number { get; set; }
        public string Student_Nationality { get; set; }
        public string Race { get; set; }
        public string Title { get; set; }
        public string Gender { get; set; }
        public System.DateTime Date_Of_Birth { get; set; }
        public string Marital_Status { get; set; }
        public string Student_Email { get; set; }
        public decimal Student_Cellphone_Number { get; set; }
        public string Student_Postal_Address { get; set; }
        public byte[] Upload_Identity_Document { get; set; }
        public byte[] Upload_Residential_Document { get; set; }
    }
}
